apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: enerlink
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/enerlink/demo:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: jenkins-demo
